{
    name: release + npm,
    on: { push: { branches: ['main'] } },
    env:
        {
            NPM_AUTH_TOKEN: '${{ secrets.NPM_AUTOMATION_KEY }}',
        },
    jobs:
        {
            build:
                {
                    runs-on: ubuntu-latest,
                    steps:
                        [
                            {
                                uses: actions/checkout@v2,
                            },
                            {
                                name: 'read .nvmrc',
                                run: 'echo "##[set-output name=NVMRC;]$(cat .nvmrc)"',
                                id: nvm,
                            },

                            {
                                uses: actions/setup-node@v2,
                                with:
                                    {
                                        node-version: '${{ steps.nvm.outputs.NVMRC }}',
                                        registry-url: 'https://registry.npmjs.org',
                                        scope: '@nuggxyz',
                                    },
                            },
                            { run: yarn },
                            {
                                run: 'yarn config set npmAuthToken $NPM_AUTH_TOKEN',
                            },
                            {
                                run: 'yarn workspaces foreach run build',
                            },
                            {
                                uses: marvinpinto/action-automatic-releases@latest,
                                with:
                                    {
                                        repo_token: '${{ secrets.GITHUB_TOKEN }}',
                                        prerelease: true,
                                    },
                            },
                        ],
                },
        },
}
